import { useEffect, useMemo, useState } from "react";
import {
  createDefaultPrintLayoutBlocks,
  createDefaultReportPrintTemplate,
} from "../../shared/defaults";
import type {
  PrintLayoutBlock,
  PrintLayoutBlockType,
  ReportPrintTemplate,
} from "../../shared/types";
import { DeleteIcon, PlusIcon } from "./AppIcons";

interface PrintDesignerProps {
  template: ReportPrintTemplate;
  companyName: string;
  generatedBy: string;
  timeSourceLabel: string;
  disabled?: boolean;
  onChange: (next: ReportPrintTemplate) => void;
}

interface BlockLibraryEntry {
  type: PrintLayoutBlockType;
  label: string;
  description: string;
  unique: boolean;
}

const BLOCK_LIBRARY: BlockLibraryEntry[] = [
  { type: "company-name", label: "Company Name", description: "Shows the workspace company.", unique: true },
  { type: "report-title", label: "Report Title", description: "Displays the live report title.", unique: true },
  { type: "report-subtitle", label: "Report Subtitle", description: "Displays the live report subtitle.", unique: true },
  { type: "header-note", label: "Header Note", description: "Shows a custom note under the title.", unique: true },
  { type: "generated-by", label: "Generated By", description: "Shows the report owner.", unique: true },
  { type: "generated-at", label: "Generated At", description: "Shows the generated timestamp.", unique: true },
  { type: "filters", label: "Filters", description: "Shows the report filters.", unique: true },
  { type: "summary", label: "Summary", description: "Shows summary metrics.", unique: true },
  { type: "report-sections", label: "Report Sections", description: "Shows the main report tables.", unique: true },
  { type: "footer-note", label: "Footer Note", description: "Shows a footer note at the end.", unique: true },
  { type: "signatures", label: "Signatures", description: "Adds signature lines.", unique: true },
  { type: "custom-text", label: "Custom Text", description: "Adds custom freeform text.", unique: false },
];

function nextBlockId(type: PrintLayoutBlockType): string {
  return `blk-${type}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

function syncTemplateWithBlocks(
  template: ReportPrintTemplate,
  layoutBlocks: PrintLayoutBlock[],
): ReportPrintTemplate {
  const enabledTypes = new Set(
    layoutBlocks.filter((block) => block.enabled).map((block) => block.type),
  );

  return {
    ...template,
    layoutBlocks,
    showCompanyName: enabledTypes.has("company-name"),
    showGeneratedBy: enabledTypes.has("generated-by"),
    showGeneratedAt: enabledTypes.has("generated-at"),
    showFilters: enabledTypes.has("filters"),
    showSummary: enabledTypes.has("summary"),
    showSignatures: enabledTypes.has("signatures"),
  };
}

function createBlock(type: PrintLayoutBlockType, template: ReportPrintTemplate): PrintLayoutBlock {
  switch (type) {
    case "header-note":
      return {
        id: nextBlockId(type),
        type,
        label: "Header Note",
        enabled: true,
        content: template.headerNote,
      };
    case "footer-note":
      return {
        id: nextBlockId(type),
        type,
        label: "Footer Note",
        enabled: true,
        content: template.footerNote,
      };
    case "custom-text":
      return {
        id: nextBlockId(type),
        type,
        label: "Custom Text",
        enabled: true,
        content: "Add your own text here.",
      };
    default: {
      const defaultBlock = createDefaultPrintLayoutBlocks().find((block) => block.type === type);
      return {
        id: nextBlockId(type),
        type,
        label: defaultBlock?.label ?? "Print Block",
        enabled: true,
        content: defaultBlock?.content ?? "",
      };
    }
  }
}

function reorderBlocks(
  layoutBlocks: PrintLayoutBlock[],
  draggedId: string,
  targetId: string,
): PrintLayoutBlock[] {
  const currentIndex = layoutBlocks.findIndex((block) => block.id === draggedId);
  const targetIndex = layoutBlocks.findIndex((block) => block.id === targetId);

  if (currentIndex < 0 || targetIndex < 0 || currentIndex === targetIndex) {
    return layoutBlocks;
  }

  const next = [...layoutBlocks];
  const [dragged] = next.splice(currentIndex, 1);
  next.splice(targetIndex, 0, dragged);
  return next;
}

function previewValue(
  block: PrintLayoutBlock,
  template: ReportPrintTemplate,
  companyName: string,
  generatedBy: string,
  timeSourceLabel: string,
): string {
  switch (block.type) {
    case "company-name":
      return companyName;
    case "report-title":
      return "Inventory Analysis Report";
    case "report-subtitle":
      return "Prepared from the current OmniStock filters";
    case "header-note":
      return template.headerNote || block.content || "Warehouse Intelligence Report";
    case "generated-by":
      return generatedBy;
    case "generated-at":
      return `${timeSourceLabel} timestamp`;
    case "filters":
      return "Location: All | Date: Last 7 days";
    case "summary":
      return "4 summary metrics";
    case "report-sections":
      return "Main report tables and detail sections";
    case "footer-note":
      return template.footerNote || block.content || "Prepared in OmniStock";
    case "signatures":
      return `${template.signatureLabelLeft} / ${template.signatureLabelRight}`;
    case "custom-text":
      return block.content || "Custom note";
    default:
      return "";
  }
}

export function PrintDesigner({
  template,
  companyName,
  generatedBy,
  timeSourceLabel,
  disabled = false,
  onChange,
}: PrintDesignerProps) {
  const [selectedBlockId, setSelectedBlockId] = useState(template.layoutBlocks[0]?.id ?? "");
  const [pendingType, setPendingType] = useState<PrintLayoutBlockType>("custom-text");
  const [draggedBlockId, setDraggedBlockId] = useState<string | null>(null);

  const layoutBlocks = useMemo(
    () =>
      template.layoutBlocks.length
        ? template.layoutBlocks
        : createDefaultReportPrintTemplate(companyName).layoutBlocks,
    [companyName, template.layoutBlocks],
  );

  const selectedBlock =
    layoutBlocks.find((block) => block.id === selectedBlockId) ?? layoutBlocks[0] ?? null;

  useEffect(() => {
    if (!layoutBlocks.length) {
      setSelectedBlockId("");
      return;
    }
    if (!selectedBlock || !layoutBlocks.some((block) => block.id === selectedBlock.id)) {
      setSelectedBlockId(layoutBlocks[0].id);
    }
  }, [layoutBlocks, selectedBlock]);

  const availableBlocks = useMemo(
    () =>
      BLOCK_LIBRARY.filter((entry) => {
        if (!entry.unique) {
          return true;
        }
        return !layoutBlocks.some((block) => block.type === entry.type);
      }),
    [layoutBlocks],
  );

  useEffect(() => {
    if (!availableBlocks.some((entry) => entry.type === pendingType)) {
      setPendingType(availableBlocks[0]?.type ?? "custom-text");
    }
  }, [availableBlocks, pendingType]);

  function updateTemplate(next: ReportPrintTemplate) {
    onChange(next);
  }

  function updateBlocks(nextBlocks: PrintLayoutBlock[]) {
    updateTemplate(syncTemplateWithBlocks(template, nextBlocks));
  }

  function patchSelectedBlock(patch: Partial<PrintLayoutBlock>) {
    if (!selectedBlock) {
      return;
    }

    const nextBlocks = layoutBlocks.map((block) =>
      block.id === selectedBlock.id ? { ...block, ...patch } : block,
    );
    updateBlocks(nextBlocks);
  }

  function addBlock() {
    if (disabled || !availableBlocks.length) {
      return;
    }

    const nextBlock = createBlock(pendingType, template);
    updateBlocks([...layoutBlocks, nextBlock]);
    setSelectedBlockId(nextBlock.id);
  }

  function moveSelectedBlock(direction: -1 | 1) {
    if (!selectedBlock || disabled) {
      return;
    }

    const currentIndex = layoutBlocks.findIndex((block) => block.id === selectedBlock.id);
    const nextIndex = currentIndex + direction;
    if (currentIndex < 0 || nextIndex < 0 || nextIndex >= layoutBlocks.length) {
      return;
    }

    const nextBlocks = [...layoutBlocks];
    const [block] = nextBlocks.splice(currentIndex, 1);
    nextBlocks.splice(nextIndex, 0, block);
    updateBlocks(nextBlocks);
  }

  function removeSelectedBlock() {
    if (!selectedBlock || disabled) {
      return;
    }
    const nextBlocks = layoutBlocks.filter((block) => block.id !== selectedBlock.id);
    updateBlocks(nextBlocks);
    setSelectedBlockId(nextBlocks[0]?.id ?? "");
  }

  function handleDrop(targetId: string) {
    if (!draggedBlockId || disabled) {
      return;
    }
    updateBlocks(reorderBlocks(layoutBlocks, draggedBlockId, targetId));
    setDraggedBlockId(null);
  }

  function updateSelectedContent(value: string) {
    if (!selectedBlock) {
      return;
    }

    if (selectedBlock.type === "header-note") {
      const nextBlocks = layoutBlocks.map((block) =>
        block.id === selectedBlock.id ? { ...block, content: value } : block,
      );
      updateTemplate(syncTemplateWithBlocks({ ...template, headerNote: value }, nextBlocks));
      return;
    }

    if (selectedBlock.type === "footer-note") {
      const nextBlocks = layoutBlocks.map((block) =>
        block.id === selectedBlock.id ? { ...block, content: value } : block,
      );
      updateTemplate(syncTemplateWithBlocks({ ...template, footerNote: value }, nextBlocks));
      return;
    }

    patchSelectedBlock({ content: value });
  }

  function previewBlock(block: PrintLayoutBlock) {
    const selected = selectedBlock?.id === block.id;
    return (
      <button
        key={block.id}
        type="button"
        draggable={!disabled}
        onClick={() => setSelectedBlockId(block.id)}
        onDragStart={() => setDraggedBlockId(block.id)}
        onDragOver={(event) => event.preventDefault()}
        onDrop={() => handleDrop(block.id)}
        onDragEnd={() => setDraggedBlockId(null)}
        className={`print-designer-block${selected ? " is-selected" : ""}${block.enabled ? "" : " is-disabled"}`}
      >
        <span className="print-designer-block-label">{block.label}</span>
        <strong>{previewValue(block, template, companyName, generatedBy, timeSourceLabel)}</strong>
        {block.type === "summary" ? (
          <div className="print-designer-summary">
            <span>Accuracy 98%</span>
            <span>Stockouts 4</span>
            <span>Value $12,400</span>
          </div>
        ) : null}
        {block.type === "report-sections" ? (
          <div className="print-designer-table">
            <div className="print-designer-table-row is-head">
              <span>Item</span>
              <span>Qty</span>
              <span>Status</span>
            </div>
            <div className="print-designer-table-row">
              <span>Chicken Breast</span>
              <span>42</span>
              <span>Healthy</span>
            </div>
            <div className="print-designer-table-row">
              <span>Dairy Cream</span>
              <span>8</span>
              <span>Low</span>
            </div>
          </div>
        ) : null}
      </button>
    );
  }

  return (
    <div className="print-designer-shell">
      <div className="print-designer-sidebar">
        <div className="panel-heading compact-heading">
          <div>
            <p className="eyebrow">Field Palette</p>
            <h3>Build the default print flow</h3>
          </div>
        </div>

        <div className="print-designer-add">
          <label className="field field-wide">
            <span>Add field</span>
            <select
              value={pendingType}
              disabled={disabled || !availableBlocks.length}
              onChange={(event) => setPendingType(event.target.value as PrintLayoutBlockType)}
            >
              {availableBlocks.map((entry) => (
                <option key={entry.type} value={entry.type}>
                  {entry.label}
                </option>
              ))}
            </select>
          </label>
          <button
            type="button"
            className="primary-button"
            disabled={disabled || !availableBlocks.length}
            onClick={addBlock}
          >
            <PlusIcon size={16} />
            <span>Add field</span>
          </button>
        </div>

        <div className="stack-list">
          {BLOCK_LIBRARY.map((entry) => (
            <div key={entry.type} className="list-row">
              <div>
                <strong>{entry.label}</strong>
                <p>{entry.description}</p>
              </div>
              <span className="status-chip neutral">
                {layoutBlocks.some((block) => block.type === entry.type) && entry.unique
                  ? "Added"
                  : entry.unique
                    ? "Available"
                    : "Repeatable"}
              </span>
            </div>
          ))}
        </div>

        {selectedBlock ? (
          <div className="print-designer-inspector">
            <div className="panel-heading compact-heading">
              <div>
                <p className="eyebrow">Selected Field</p>
                <h3>{selectedBlock.label}</h3>
              </div>
            </div>

            <div className="page-stack">
              <label className="field field-wide">
                <span>Field label</span>
                <input
                  value={selectedBlock.label}
                  disabled={disabled}
                  onChange={(event) => patchSelectedBlock({ label: event.target.value })}
                />
              </label>

              {selectedBlock.type === "custom-text" ||
              selectedBlock.type === "header-note" ||
              selectedBlock.type === "footer-note" ? (
                <label className="field field-wide">
                  <span>Field content</span>
                  <textarea
                    value={
                      selectedBlock.type === "header-note"
                        ? template.headerNote
                        : selectedBlock.type === "footer-note"
                          ? template.footerNote
                          : selectedBlock.content
                    }
                    disabled={disabled}
                    rows={4}
                    onChange={(event) => updateSelectedContent(event.target.value)}
                  />
                </label>
              ) : null}

              {selectedBlock.type === "signatures" ? (
                <div className="settings-fields-grid">
                  <label className="settings-field-card">
                    <span className="settings-field-label">Left label</span>
                    <input
                      value={template.signatureLabelLeft}
                      disabled={disabled}
                      onChange={(event) =>
                        updateTemplate({ ...template, signatureLabelLeft: event.target.value })
                      }
                    />
                  </label>
                  <label className="settings-field-card">
                    <span className="settings-field-label">Right label</span>
                    <input
                      value={template.signatureLabelRight}
                      disabled={disabled}
                      onChange={(event) =>
                        updateTemplate({ ...template, signatureLabelRight: event.target.value })
                      }
                    />
                  </label>
                </div>
              ) : null}

              <label className="list-row">
                <div>
                  <strong>Visible in output</strong>
                  <p>Hide or show this field in the saved print layout.</p>
                </div>
                <input
                  type="checkbox"
                  checked={selectedBlock.enabled}
                  disabled={disabled}
                  onChange={(event) => patchSelectedBlock({ enabled: event.target.checked })}
                />
              </label>

              <div className="button-row">
                <button
                  type="button"
                  className="secondary-button"
                  disabled={disabled}
                  onClick={() => moveSelectedBlock(-1)}
                >
                  Move up
                </button>
                <button
                  type="button"
                  className="secondary-button"
                  disabled={disabled}
                  onClick={() => moveSelectedBlock(1)}
                >
                  Move down
                </button>
                <button
                  type="button"
                  className="danger-button"
                  disabled={disabled}
                  onClick={removeSelectedBlock}
                >
                  <DeleteIcon size={16} />
                  <span>Remove</span>
                </button>
              </div>
            </div>
          </div>
        ) : null}
      </div>

      <div className="print-designer-preview">
        <div className="panel-heading compact-heading">
          <div>
            <p className="eyebrow">A4 Preview</p>
            <h3>Drag fields to change the saved print order</h3>
          </div>
          <span className="status-chip neutral">
            {template.orientation === "landscape" ? "Landscape" : "Portrait"}
          </span>
        </div>

        <div
          className={`print-designer-page${
            template.orientation === "landscape" ? " is-landscape" : ""
          }`}
          style={{ borderColor: `${template.accentColor}40` }}
        >
          <div className="print-designer-page-inner" style={{ borderColor: template.accentColor }}>
            {layoutBlocks.map((block) => previewBlock(block))}
          </div>
        </div>
      </div>
    </div>
  );
}
