import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import {
  createDefaultPrintLayoutBlocks,
  createDefaultReportPrintTemplate,
} from "../../shared/defaults";
import type {
  PrintLayoutBlock,
  PrintLayoutBlockType,
  ReportPrintTemplate,
} from "../../shared/types";
import { CloseIcon, DeleteIcon, PlusIcon } from "./AppIcons";

interface PrintDesignerProps {
  template: ReportPrintTemplate;
  companyName: string;
  generatedBy: string;
  timeSourceLabel: string;
  disabled?: boolean;
  onChange: (next: ReportPrintTemplate) => void;
}

interface BlockLibraryEntry {
  type: PrintLayoutBlockType;
  label: string;
  description: string;
  unique: boolean;
}

interface DragState {
  blockId: string;
  offsetXPct: number;
  offsetYPct: number;
}

const BLOCK_LIBRARY: BlockLibraryEntry[] = [
  { type: "company-name", label: "Company Name", description: "Shows the workspace company.", unique: true },
  { type: "report-title", label: "Report Title", description: "Displays the live report title.", unique: true },
  { type: "report-subtitle", label: "Report Subtitle", description: "Displays the live report subtitle.", unique: true },
  { type: "header-note", label: "Header Note", description: "Shows a custom note under the title.", unique: true },
  { type: "generated-by", label: "Generated By", description: "Shows the report owner.", unique: true },
  { type: "generated-at", label: "Generated At", description: "Shows the generated timestamp.", unique: true },
  { type: "filters", label: "Filters", description: "Shows the report filters.", unique: true },
  { type: "summary", label: "Summary", description: "Shows summary metrics.", unique: true },
  { type: "report-sections", label: "Report Sections", description: "Shows the main report tables.", unique: true },
  { type: "footer-note", label: "Footer Note", description: "Shows a footer note at the end.", unique: true },
  { type: "signatures", label: "Signatures", description: "Adds signature lines.", unique: true },
  { type: "custom-text", label: "Custom Text", description: "Adds custom freeform text.", unique: false },
];

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value));
}

function nextBlockId(type: PrintLayoutBlockType): string {
  return `blk-${type}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
}

function syncTemplateWithBlocks(
  template: ReportPrintTemplate,
  layoutBlocks: PrintLayoutBlock[],
): ReportPrintTemplate {
  const enabledTypes = new Set(
    layoutBlocks.filter((block) => block.enabled).map((block) => block.type),
  );

  return {
    ...template,
    layoutBlocks,
    showCompanyName: enabledTypes.has("company-name"),
    showGeneratedBy: enabledTypes.has("generated-by"),
    showGeneratedAt: enabledTypes.has("generated-at"),
    showFilters: enabledTypes.has("filters"),
    showSummary: enabledTypes.has("summary"),
    showSignatures: enabledTypes.has("signatures"),
  };
}

function createBlock(type: PrintLayoutBlockType, template: ReportPrintTemplate): PrintLayoutBlock {
  const defaults = createDefaultPrintLayoutBlocks();
  const defaultBlock = defaults.find((block) => block.type === type) ?? defaults[0];
  const duplicateCount = template.layoutBlocks.filter((block) => block.type === type).length;
  const baseBlock: PrintLayoutBlock =
    type === "header-note"
      ? {
          ...defaultBlock,
          id: nextBlockId(type),
          label: "Header Note",
          content: template.headerNote,
        }
      : type === "footer-note"
        ? {
            ...defaultBlock,
            id: nextBlockId(type),
            label: "Footer Note",
            content: template.footerNote,
          }
        : type === "custom-text"
          ? {
              ...defaultBlock,
              id: nextBlockId(type),
              type,
              label: "Custom Text",
              content: "Add your own text here.",
            }
          : {
              ...defaultBlock,
              id: nextBlockId(type),
            };

  return {
    ...baseBlock,
    x: clamp(baseBlock.x + duplicateCount * 3, 0, 90),
    y: clamp(baseBlock.y + duplicateCount * 3, 0, 94),
    z: baseBlock.z + duplicateCount,
  };
}

function previewValue(
  block: PrintLayoutBlock,
  template: ReportPrintTemplate,
  companyName: string,
  generatedBy: string,
  timeSourceLabel: string,
): string {
  switch (block.type) {
    case "company-name":
      return companyName;
    case "report-title":
      return "Inventory Analysis Report";
    case "report-subtitle":
      return "Prepared from the current OmniStock filters";
    case "header-note":
      return template.headerNote || block.content || "Warehouse Intelligence Report";
    case "generated-by":
      return generatedBy;
    case "generated-at":
      return `${timeSourceLabel} timestamp`;
    case "filters":
      return "Location: All | Date: Last 7 days";
    case "summary":
      return "4 summary metrics";
    case "report-sections":
      return "Main report tables and detail sections";
    case "footer-note":
      return template.footerNote || block.content || "Prepared in OmniStock";
    case "signatures":
      return `${template.signatureLabelLeft} / ${template.signatureLabelRight}`;
    case "custom-text":
      return block.content || "Custom note";
    default:
      return "";
  }
}

function paperSizeLabel(template: ReportPrintTemplate): string {
  const size = template.paperSize.toUpperCase();
  const orientation = template.orientation === "landscape" ? "Landscape" : "Portrait";
  return `${size} · ${orientation}`;
}

function actualPaperDimensions(template: ReportPrintTemplate): string {
  if (template.orientation === "landscape") {
    return template.paperSize === "letter" ? "279.4mm × 215.9mm" : "297mm × 210mm";
  }
  return template.paperSize === "letter" ? "215.9mm × 279.4mm" : "210mm × 297mm";
}

export function PrintDesigner({
  template,
  companyName,
  generatedBy,
  timeSourceLabel,
  disabled = false,
  onChange,
}: PrintDesignerProps) {
  const previewRef = useRef<HTMLDivElement | null>(null);
  const [selectedBlockId, setSelectedBlockId] = useState(template.layoutBlocks[0]?.id ?? "");
  const [pendingType, setPendingType] = useState<PrintLayoutBlockType>("custom-text");
  const [dragState, setDragState] = useState<DragState | null>(null);
  const [editorOpen, setEditorOpen] = useState(false);

  const layoutBlocks = useMemo(
    () =>
      template.layoutBlocks.length
        ? template.layoutBlocks
        : createDefaultReportPrintTemplate(companyName).layoutBlocks,
    [companyName, template.layoutBlocks],
  );

  const selectedBlock =
    layoutBlocks.find((block) => block.id === selectedBlockId) ?? layoutBlocks[0] ?? null;

  useEffect(() => {
    if (!layoutBlocks.length) {
      setSelectedBlockId("");
      return;
    }
    if (!selectedBlock || !layoutBlocks.some((block) => block.id === selectedBlock.id)) {
      setSelectedBlockId(layoutBlocks[0].id);
    }
  }, [layoutBlocks, selectedBlock]);

  const availableBlocks = useMemo(
    () =>
      BLOCK_LIBRARY.filter((entry) => {
        if (!entry.unique) {
          return true;
        }
        return !layoutBlocks.some((block) => block.type === entry.type);
      }),
    [layoutBlocks],
  );

  useEffect(() => {
    if (!availableBlocks.some((entry) => entry.type === pendingType)) {
      setPendingType(availableBlocks[0]?.type ?? "custom-text");
    }
  }, [availableBlocks, pendingType]);

  useEffect(() => {
    if (!editorOpen || !dragState || disabled) {
      return;
    }

    const activeDrag = dragState;

    function handlePointerMove(event: PointerEvent) {
      const preview = previewRef.current;
      if (!preview) {
        return;
      }

      const rect = preview.getBoundingClientRect();
      const pointerXPct = ((event.clientX - rect.left) / rect.width) * 100;
      const pointerYPct = ((event.clientY - rect.top) / rect.height) * 100;
      const targetBlock = layoutBlocks.find((block) => block.id === activeDrag.blockId);
      if (!targetBlock) {
        return;
      }

      const nextX = clamp(pointerXPct - activeDrag.offsetXPct, 0, 100 - targetBlock.width);
      const nextY = clamp(pointerYPct - activeDrag.offsetYPct, 0, 100);
      const nextBlocks = layoutBlocks.map((block) =>
        block.id === activeDrag.blockId
          ? {
              ...block,
              x: Number(nextX.toFixed(2)),
              y: Number(nextY.toFixed(2)),
            }
          : block,
      );

      onChange(syncTemplateWithBlocks(template, nextBlocks));
    }

    function handlePointerUp() {
      setDragState(null);
    }

    window.addEventListener("pointermove", handlePointerMove);
    window.addEventListener("pointerup", handlePointerUp);

    return () => {
      window.removeEventListener("pointermove", handlePointerMove);
      window.removeEventListener("pointerup", handlePointerUp);
    };
  }, [disabled, dragState, editorOpen, layoutBlocks, onChange, template]);

  useEffect(() => {
    if (!editorOpen || typeof document === "undefined") {
      return;
    }

    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";

    function handleKeyDown(event: KeyboardEvent) {
      if (event.key === "Escape") {
        setEditorOpen(false);
      }
    }

    window.addEventListener("keydown", handleKeyDown);

    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", handleKeyDown);
    };
  }, [editorOpen]);

  function updateTemplate(next: ReportPrintTemplate) {
    onChange(next);
  }

  function updateBlocks(nextBlocks: PrintLayoutBlock[]) {
    updateTemplate(syncTemplateWithBlocks(template, nextBlocks));
  }

  function patchSelectedBlock(patch: Partial<PrintLayoutBlock>) {
    if (!selectedBlock) {
      return;
    }

    const nextBlocks = layoutBlocks.map((block) =>
      block.id === selectedBlock.id ? { ...block, ...patch } : block,
    );
    updateBlocks(nextBlocks);
  }

  function addBlock() {
    if (disabled || !availableBlocks.length) {
      return;
    }

    const nextBlock = createBlock(pendingType, template);
    updateBlocks([...layoutBlocks, nextBlock]);
    setSelectedBlockId(nextBlock.id);
  }

  function removeSelectedBlock() {
    if (!selectedBlock || disabled) {
      return;
    }

    const nextBlocks = layoutBlocks.filter((block) => block.id !== selectedBlock.id);
    updateBlocks(nextBlocks);
    setSelectedBlockId(nextBlocks[0]?.id ?? "");
  }

  function updateSelectedContent(value: string) {
    if (!selectedBlock) {
      return;
    }

    if (selectedBlock.type === "header-note") {
      const nextBlocks = layoutBlocks.map((block) =>
        block.id === selectedBlock.id ? { ...block, content: value } : block,
      );
      updateTemplate(syncTemplateWithBlocks({ ...template, headerNote: value }, nextBlocks));
      return;
    }

    if (selectedBlock.type === "footer-note") {
      const nextBlocks = layoutBlocks.map((block) =>
        block.id === selectedBlock.id ? { ...block, content: value } : block,
      );
      updateTemplate(syncTemplateWithBlocks({ ...template, footerNote: value }, nextBlocks));
      return;
    }

    patchSelectedBlock({ content: value });
  }

  function updateSelectedNumberField(
    field: keyof Pick<PrintLayoutBlock, "x" | "y" | "z" | "width" | "minHeight">,
    rawValue: string,
  ) {
    if (!selectedBlock) {
      return;
    }

    const numericValue = Number(rawValue || 0);
    if (!Number.isFinite(numericValue)) {
      return;
    }

    switch (field) {
      case "x":
        patchSelectedBlock({ x: clamp(numericValue, 0, 100 - selectedBlock.width) });
        break;
      case "y":
        patchSelectedBlock({ y: clamp(numericValue, 0, 100) });
        break;
      case "z":
        patchSelectedBlock({ z: clamp(Math.round(numericValue), 0, 20) });
        break;
      case "width": {
        const nextWidth = clamp(numericValue, 10, 100);
        patchSelectedBlock({
          width: nextWidth,
          x: clamp(selectedBlock.x, 0, 100 - nextWidth),
        });
        break;
      }
      case "minHeight":
        patchSelectedBlock({ minHeight: clamp(numericValue, 48, 960) });
        break;
      default:
        break;
    }
  }

  function handlePreviewPointerDown(
    event: React.PointerEvent<HTMLButtonElement>,
    block: PrintLayoutBlock,
  ) {
    if (disabled || !previewRef.current) {
      return;
    }

    event.preventDefault();
    const rect = previewRef.current.getBoundingClientRect();
    const offsetXPct = ((event.clientX - rect.left) / rect.width) * 100 - block.x;
    const offsetYPct = ((event.clientY - rect.top) / rect.height) * 100 - block.y;
    setSelectedBlockId(block.id);
    setDragState({
      blockId: block.id,
      offsetXPct,
      offsetYPct,
    });
  }

  function previewBlock(block: PrintLayoutBlock) {
    const selected = selectedBlock?.id === block.id;
    return (
      <button
        key={block.id}
        type="button"
        onClick={() => setSelectedBlockId(block.id)}
        onPointerDown={(event) => handlePreviewPointerDown(event, block)}
        className={`print-designer-block${selected ? " is-selected" : ""}${block.enabled ? "" : " is-disabled"}`}
        style={{
          left: `${block.x}%`,
          top: `${block.y}%`,
          width: `${block.width}%`,
          minHeight: `${block.minHeight}px`,
          zIndex: block.z,
        }}
      >
        <span className="print-designer-block-label">{block.label}</span>
        <strong>{previewValue(block, template, companyName, generatedBy, timeSourceLabel)}</strong>
        {block.type === "summary" ? (
          <div className="print-designer-summary">
            <span>Accuracy 98%</span>
            <span>Stockouts 4</span>
            <span>Value $12,400</span>
          </div>
        ) : null}
        {block.type === "report-sections" ? (
          <div className="print-designer-table">
            <div className="print-designer-table-row is-head">
              <span>Item</span>
              <span>Qty</span>
              <span>Status</span>
            </div>
            <div className="print-designer-table-row">
              <span>Chicken Breast</span>
              <span>42</span>
              <span>Healthy</span>
            </div>
            <div className="print-designer-table-row">
              <span>Dairy Cream</span>
              <span>8</span>
              <span>Low</span>
            </div>
          </div>
        ) : null}
      </button>
    );
  }

  const editorSidebar = (
    <div className="print-designer-modal-sidebar">
      <div className="print-designer-add">
        <div className="panel-heading compact-heading">
          <div>
            <p className="eyebrow">Field Palette</p>
            <h3>Build the default print flow</h3>
          </div>
        </div>

        <label className="field field-wide">
          <span>Add field</span>
          <select
            value={pendingType}
            disabled={disabled || !availableBlocks.length}
            onChange={(event) => setPendingType(event.target.value as PrintLayoutBlockType)}
          >
            {availableBlocks.map((entry) => (
              <option key={entry.type} value={entry.type}>
                {entry.label}
              </option>
            ))}
          </select>
        </label>
        <button
          type="button"
          className="primary-button"
          disabled={disabled || !availableBlocks.length}
          onClick={addBlock}
        >
          <PlusIcon size={16} />
          <span>Add field</span>
        </button>
      </div>

      <div className="stack-list">
        {BLOCK_LIBRARY.map((entry) => (
          <div key={entry.type} className="list-row">
            <div>
              <strong>{entry.label}</strong>
              <p>{entry.description}</p>
            </div>
            <span className="status-chip neutral">
              {layoutBlocks.some((block) => block.type === entry.type) && entry.unique
                ? "Added"
                : entry.unique
                  ? "Available"
                  : "Repeatable"}
            </span>
          </div>
        ))}
      </div>

      {selectedBlock ? (
        <div className="print-designer-inspector">
          <div className="panel-heading compact-heading">
            <div>
              <p className="eyebrow">Selected Field</p>
              <h3>{selectedBlock.label}</h3>
            </div>
            <span className="status-chip neutral">Layer {selectedBlock.z}</span>
          </div>

          <div className="page-stack">
            <label className="field field-wide">
              <span>Field label</span>
              <input
                value={selectedBlock.label}
                disabled={disabled}
                onChange={(event) => patchSelectedBlock({ label: event.target.value })}
              />
            </label>

            {selectedBlock.type === "custom-text" ||
            selectedBlock.type === "header-note" ||
            selectedBlock.type === "footer-note" ? (
              <label className="field field-wide">
                <span>Field content</span>
                <textarea
                  value={
                    selectedBlock.type === "header-note"
                      ? template.headerNote
                      : selectedBlock.type === "footer-note"
                        ? template.footerNote
                        : selectedBlock.content
                  }
                  disabled={disabled}
                  rows={4}
                  onChange={(event) => updateSelectedContent(event.target.value)}
                />
              </label>
            ) : null}

            {selectedBlock.type === "signatures" ? (
              <div className="settings-fields-grid compact-grid">
                <label className="settings-field-card">
                  <span className="settings-field-label">Left label</span>
                  <input
                    value={template.signatureLabelLeft}
                    disabled={disabled}
                    onChange={(event) =>
                      updateTemplate({ ...template, signatureLabelLeft: event.target.value })
                    }
                  />
                </label>
                <label className="settings-field-card">
                  <span className="settings-field-label">Right label</span>
                  <input
                    value={template.signatureLabelRight}
                    disabled={disabled}
                    onChange={(event) =>
                      updateTemplate({ ...template, signatureLabelRight: event.target.value })
                    }
                  />
                </label>
              </div>
            ) : null}

            <div className="settings-fields-grid compact-grid">
              <label className="settings-field-card">
                <span className="settings-field-label">X Position (%)</span>
                <input
                  type="number"
                  min="0"
                  max={Math.max(0, 100 - selectedBlock.width)}
                  value={selectedBlock.x}
                  disabled={disabled}
                  onChange={(event) => updateSelectedNumberField("x", event.target.value)}
                />
              </label>
              <label className="settings-field-card">
                <span className="settings-field-label">Y Position (%)</span>
                <input
                  type="number"
                  min="0"
                  max="100"
                  value={selectedBlock.y}
                  disabled={disabled}
                  onChange={(event) => updateSelectedNumberField("y", event.target.value)}
                />
              </label>
              <label className="settings-field-card">
                <span className="settings-field-label">Z Layer</span>
                <input
                  type="number"
                  min="0"
                  max="20"
                  value={selectedBlock.z}
                  disabled={disabled}
                  onChange={(event) => updateSelectedNumberField("z", event.target.value)}
                />
              </label>
              <label className="settings-field-card">
                <span className="settings-field-label">Width (%)</span>
                <input
                  type="number"
                  min="10"
                  max="100"
                  value={selectedBlock.width}
                  disabled={disabled}
                  onChange={(event) => updateSelectedNumberField("width", event.target.value)}
                />
              </label>
              <label className="settings-field-card">
                <span className="settings-field-label">Height (px)</span>
                <input
                  type="number"
                  min="48"
                  max="960"
                  value={selectedBlock.minHeight}
                  disabled={disabled}
                  onChange={(event) => updateSelectedNumberField("minHeight", event.target.value)}
                />
              </label>
            </div>

            <label className="list-row">
              <div>
                <strong>Visible in output</strong>
                <p>Hide or show this field in the saved print layout.</p>
              </div>
              <input
                type="checkbox"
                checked={selectedBlock.enabled}
                disabled={disabled}
                onChange={(event) => patchSelectedBlock({ enabled: event.target.checked })}
              />
            </label>

            <div className="button-row">
              <button
                type="button"
                className="secondary-button"
                disabled={disabled}
                onClick={() => patchSelectedBlock({ z: clamp(selectedBlock.z + 1, 0, 20) })}
              >
                Bring forward
              </button>
              <button
                type="button"
                className="secondary-button"
                disabled={disabled}
                onClick={() => patchSelectedBlock({ z: clamp(selectedBlock.z - 1, 0, 20) })}
              >
                Send back
              </button>
              <button
                type="button"
                className="danger-button"
                disabled={disabled}
                onClick={removeSelectedBlock}
              >
                <DeleteIcon size={16} />
                <span>Remove</span>
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  );

  const editorCanvas = (
    <div className="print-designer-modal-canvas">
      <div className="print-designer-canvas-meta">
        <div>
          <p className="eyebrow">A4 Preview</p>
          <h3>Full-size popup canvas</h3>
          <p className="helper-text">
            Browser-calibrated paper size using millimetres for easier positioning and resizing.
          </p>
        </div>
        <div className="chip-row">
          <span className="status-chip neutral">{paperSizeLabel(template)}</span>
          <span className="status-chip neutral">{actualPaperDimensions(template)}</span>
        </div>
      </div>

      <div className="print-designer-canvas-scroll">
        <div
          ref={previewRef}
          className={`print-designer-sheet${
            template.orientation === "landscape" ? " is-landscape" : ""
          }`}
          style={{ borderTopColor: template.accentColor }}
        >
          {layoutBlocks.map((block) => previewBlock(block))}
        </div>
      </div>
    </div>
  );

  const modal =
    editorOpen && typeof document !== "undefined"
      ? createPortal(
          <div
            className="print-designer-modal-scrim"
            role="presentation"
            onClick={() => setEditorOpen(false)}
          >
            <section
              className="print-designer-modal-card"
              role="dialog"
              aria-modal="true"
              aria-label="A4 print designer"
              onClick={(event) => event.stopPropagation()}
            >
              <header className="print-designer-modal-header">
                <div>
                  <p className="eyebrow">Print Designer</p>
                  <h2>Actual-size A4 popup editor</h2>
                  <p className="helper-text">
                    Move fields visually on the sheet, then save the layout as the default print
                    template.
                  </p>
                </div>
                <div className="button-row">
                  <button
                    type="button"
                    className="secondary-button"
                    onClick={() => setEditorOpen(false)}
                  >
                    <CloseIcon size={16} />
                    <span>Close</span>
                  </button>
                </div>
              </header>

              <div className="print-designer-modal-body">
                {editorSidebar}
                {editorCanvas}
              </div>
            </section>
          </div>,
          document.body,
        )
      : null;

  return (
    <>
      <div className="print-designer-launcher">
        <div className="panel-heading compact-heading">
          <div>
            <p className="eyebrow">A4 Editor</p>
            <h3>Open the popup canvas</h3>
          </div>
          <span className="status-chip neutral">{paperSizeLabel(template)}</span>
        </div>

        <p className="helper-text">
          Launch the full-size popup editor to position, layer, and resize report blocks on an
          A4 paper canvas before saving the default template.
        </p>

        <div className="settings-fields-grid compact-grid">
          <div className="settings-field-card">
            <span className="settings-field-label">Paper</span>
            <strong>{actualPaperDimensions(template)}</strong>
          </div>
          <div className="settings-field-card">
            <span className="settings-field-label">Blocks</span>
            <strong>{layoutBlocks.length} active fields</strong>
          </div>
          <div className="settings-field-card">
            <span className="settings-field-label">Editing</span>
            <strong>Drag · X/Y/Z · Width · Height</strong>
          </div>
        </div>

        <div className="button-row">
          <button
            type="button"
            className="primary-button"
            disabled={disabled}
            onClick={() => setEditorOpen(true)}
          >
            Open A4 popup editor
          </button>
        </div>
      </div>
      {modal}
    </>
  );
}
