import type {
  DailySummaryNotificationSettings,
  NotificationMessageTemplate,
  NotificationRuleSettings,
  NotificationSettings,
  NotificationStyleSettings,
  PrintLayoutBlock,
  PrintLayoutBlockType,
  PrintDensity,
  PrintOrientation,
  PrintPaperSize,
  ReportPrintTemplate,
  TimeSource,
} from "./types";

export const DEFAULT_TIME_SOURCE: TimeSource = "system";
export const DEFAULT_PRINT_PAPER_SIZE: PrintPaperSize = "a4";
export const DEFAULT_PRINT_ORIENTATION: PrintOrientation = "portrait";
export const DEFAULT_PRINT_DENSITY: PrintDensity = "comfortable";

function createNotificationRuleSettings(
  overrides: Partial<NotificationRuleSettings> = {},
): NotificationRuleSettings {
  return {
    enabled: true,
    inApp: true,
    telegram: false,
    ...overrides,
  };
}

function createDailySummarySettings(): DailySummaryNotificationSettings {
  return {
    ...createNotificationRuleSettings(),
    hour: 8,
    scope: "warehouse",
  };
}

function createNotificationStyleSettings(): NotificationStyleSettings {
  return {
    telegramHeader: "OmniStock Alert",
    telegramFooter: "Powered by OmniStock",
    includeTimestamp: true,
  };
}

function createNotificationTemplates(): Record<
  NotificationSettings["templates"] extends infer T
    ? T extends Record<infer K, NotificationMessageTemplate>
      ? K
      : never
    : never,
  NotificationMessageTemplate
> {
  return {
    "low-stock": {
      title: "Low Stock - {{itemName}}",
      body: "{{locationName}} is at {{quantity}} on hand and needs replenishment.",
    },
    "near-expiry": {
      title: "Near Expiry - {{itemName}}",
      body: "Lot {{lotCode}} at {{locationName}} expires in {{daysUntilExpiry}} days and should move first.",
    },
    expired: {
      title: "Expired Stock - {{itemName}}",
      body: "Lot {{lotCode}} at {{locationName}} is expired and should be blocked immediately.",
    },
    "approval-request": {
      title: "Approval Needed - {{reference}}",
      body: "{{requestKind}} for {{itemName}} is waiting for approval at {{locationName}}.",
    },
    "failed-sync": {
      title: "Sync Failure - {{actorName}}",
      body: "A device reported a sync failure: {{message}}",
    },
    "wastage-threshold": {
      title: "Wastage Threshold Exceeded - {{locationName}}",
      body: "Rolling 24-hour wastage reached {{totalCost}} and exceeded the configured threshold.",
    },
    "daily-summary": {
      title: "Daily Summary - {{locationName}}",
      body: "{{movementCount}} movements, {{lowStockCount}} low stock, {{nearExpiryCount}} near expiry, {{expiredCount}} expired, wastage {{wasteCost}}.",
    },
  };
}

function createPrintLayoutBlock(
  type: PrintLayoutBlockType,
  label: string,
  content = "",
): PrintLayoutBlock {
  return {
    id: `blk-${type}`,
    type,
    label,
    enabled: true,
    content,
  };
}

export function createDefaultPrintLayoutBlocks(): PrintLayoutBlock[] {
  return [
    createPrintLayoutBlock("company-name", "Company"),
    createPrintLayoutBlock("report-title", "Report Title"),
    createPrintLayoutBlock("report-subtitle", "Report Subtitle"),
    createPrintLayoutBlock("header-note", "Header Note"),
    createPrintLayoutBlock("generated-by", "Generated By"),
    createPrintLayoutBlock("generated-at", "Generated At"),
    createPrintLayoutBlock("filters", "Filters"),
    createPrintLayoutBlock("summary", "Summary"),
    createPrintLayoutBlock("report-sections", "Report Sections"),
    createPrintLayoutBlock("footer-note", "Footer Note"),
    createPrintLayoutBlock("signatures", "Signatures"),
  ];
}

export function createDefaultReportPrintTemplate(companyName = "OmniStock"): ReportPrintTemplate {
  return {
    templateName: "OmniStock Standard",
    accentColor: "#2563eb",
    paperSize: DEFAULT_PRINT_PAPER_SIZE,
    orientation: DEFAULT_PRINT_ORIENTATION,
    density: DEFAULT_PRINT_DENSITY,
    marginMm: 14,
    headerNote: "Warehouse Intelligence Report",
    footerNote: `Prepared in ${companyName}`,
    showCompanyName: true,
    showGeneratedAt: true,
    showGeneratedBy: true,
    showFilters: true,
    showSummary: true,
    showSignatures: false,
    signatureLabelLeft: "Prepared by",
    signatureLabelRight: "Approved by",
    layoutBlocks: createDefaultPrintLayoutBlocks(),
  };
}

export function createDefaultNotificationSettings(): NotificationSettings {
  return {
    telegramEnabled: false,
    telegramChatId: "",
    lowStock: createNotificationRuleSettings(),
    nearExpiry: createNotificationRuleSettings(),
    expired: createNotificationRuleSettings({ telegram: true }),
    approvalRequests: createNotificationRuleSettings({ telegram: true }),
    failedSync: createNotificationRuleSettings({ telegram: true }),
    wastageThresholdExceeded: createNotificationRuleSettings({ telegram: true }),
    dailySummary: createDailySummarySettings(),
    wastageCostThreshold: 5000,
    style: createNotificationStyleSettings(),
    templates: createNotificationTemplates(),
  };
}
