import type {
  DailySummaryNotificationSettings,
  NotificationMessageTemplate,
  NotificationRuleSettings,
  NotificationSettings,
  NotificationStyleSettings,
  PrintLayoutBlock,
  PrintLayoutBlockType,
  PrintDensity,
  PrintOrientation,
  PrintPaperSize,
  ReportPrintTemplate,
  TimeSource,
} from "./types";

export const DEFAULT_TIME_SOURCE: TimeSource = "system";
export const DEFAULT_WORKSPACE_LOCATION = "Maldives";
export const DEFAULT_CURRENCY = "MVR";
export const DEFAULT_TIMEZONE = "Indian/Maldives";
export const DEFAULT_PRINT_PAPER_SIZE: PrintPaperSize = "a4";
export const DEFAULT_PRINT_ORIENTATION: PrintOrientation = "portrait";
export const DEFAULT_PRINT_DENSITY: PrintDensity = "comfortable";

function createNotificationRuleSettings(
  overrides: Partial<NotificationRuleSettings> = {},
): NotificationRuleSettings {
  return {
    enabled: true,
    inApp: true,
    telegram: false,
    ...overrides,
  };
}

function createDailySummarySettings(): DailySummaryNotificationSettings {
  return {
    ...createNotificationRuleSettings(),
    hour: 8,
    scope: "warehouse",
  };
}

function createNotificationStyleSettings(): NotificationStyleSettings {
  return {
    telegramHeader: "OmniStock Alert",
    telegramFooter: "Powered by OmniStock",
    includeTimestamp: true,
  };
}

function createNotificationTemplates(): Record<
  NotificationSettings["templates"] extends infer T
    ? T extends Record<infer K, NotificationMessageTemplate>
      ? K
      : never
    : never,
  NotificationMessageTemplate
> {
  return {
    "low-stock": {
      title: "Low Stock - {{itemName}}",
      body: "{{locationName}} is at {{quantity}} on hand and needs replenishment.",
    },
    "near-expiry": {
      title: "Near Expiry - {{itemName}}",
      body: "Lot {{lotCode}} at {{locationName}} expires in {{daysUntilExpiry}} days and should move first.",
    },
    expired: {
      title: "Expired Stock - {{itemName}}",
      body: "Lot {{lotCode}} at {{locationName}} is expired and should be blocked immediately.",
    },
    "approval-request": {
      title: "Approval Needed - {{reference}}",
      body: "{{requestKind}} for {{itemName}} is waiting for approval at {{locationName}}.",
    },
    "failed-sync": {
      title: "Sync Failure - {{actorName}}",
      body: "A device reported a sync failure: {{message}}",
    },
    "wastage-threshold": {
      title: "Wastage Threshold Exceeded - {{locationName}}",
      body: "Rolling 24-hour wastage reached {{totalCost}} and exceeded the configured threshold.",
    },
    "daily-summary": {
      title: "Daily Summary - {{locationName}}",
      body: "{{movementCount}} movements, {{lowStockCount}} low stock, {{nearExpiryCount}} near expiry, {{expiredCount}} expired, wastage {{wasteCost}}.",
    },
  };
}

function createPrintLayoutBlock(
  type: PrintLayoutBlockType,
  label: string,
  content = "",
  layout?: Partial<Pick<PrintLayoutBlock, "x" | "y" | "z" | "width" | "minHeight">>,
): PrintLayoutBlock {
  return {
    id: `blk-${type}`,
    type,
    label,
    enabled: true,
    content,
    x: layout?.x ?? 0,
    y: layout?.y ?? 0,
    z: layout?.z ?? 1,
    width: layout?.width ?? 100,
    minHeight: layout?.minHeight ?? 72,
  };
}

export function createDefaultPrintLayoutBlocks(): PrintLayoutBlock[] {
  return [
    createPrintLayoutBlock("company-name", "Company", "", {
      x: 0,
      y: 0,
      z: 2,
      width: 42,
      minHeight: 58,
    }),
    createPrintLayoutBlock("generated-by", "Generated By", "", {
      x: 58,
      y: 0,
      z: 2,
      width: 42,
      minHeight: 58,
    }),
    createPrintLayoutBlock("report-title", "Report Title", "", {
      x: 0,
      y: 8,
      z: 3,
      width: 100,
      minHeight: 82,
    }),
    createPrintLayoutBlock("report-subtitle", "Report Subtitle", "", {
      x: 0,
      y: 18,
      z: 2,
      width: 100,
      minHeight: 62,
    }),
    createPrintLayoutBlock("header-note", "Header Note", "", {
      x: 0,
      y: 27,
      z: 2,
      width: 100,
      minHeight: 72,
    }),
    createPrintLayoutBlock("generated-at", "Generated At", "", {
      x: 0,
      y: 37,
      z: 2,
      width: 42,
      minHeight: 58,
    }),
    createPrintLayoutBlock("filters", "Filters", "", {
      x: 58,
      y: 37,
      z: 2,
      width: 42,
      minHeight: 58,
    }),
    createPrintLayoutBlock("summary", "Summary", "", {
      x: 0,
      y: 47,
      z: 1,
      width: 100,
      minHeight: 112,
    }),
    createPrintLayoutBlock("report-sections", "Report Sections", "", {
      x: 0,
      y: 63,
      z: 1,
      width: 100,
      minHeight: 240,
    }),
    createPrintLayoutBlock("footer-note", "Footer Note", "", {
      x: 0,
      y: 90,
      z: 2,
      width: 100,
      minHeight: 62,
    }),
    createPrintLayoutBlock("signatures", "Signatures", "", {
      x: 0,
      y: 99,
      z: 2,
      width: 100,
      minHeight: 88,
    }),
  ];
}

export function createDefaultReportPrintTemplate(companyName = "OmniStock"): ReportPrintTemplate {
  return {
    templateName: "OmniStock Standard",
    accentColor: "#2563eb",
    paperSize: DEFAULT_PRINT_PAPER_SIZE,
    orientation: DEFAULT_PRINT_ORIENTATION,
    density: DEFAULT_PRINT_DENSITY,
    marginMm: 14,
    headerNote: "Warehouse Intelligence Report",
    footerNote: `Prepared in ${companyName}`,
    showCompanyName: true,
    showGeneratedAt: true,
    showGeneratedBy: true,
    showFilters: true,
    showSummary: true,
    showSignatures: false,
    signatureLabelLeft: "Prepared by",
    signatureLabelRight: "Approved by",
    layoutBlocks: createDefaultPrintLayoutBlocks(),
  };
}

export function createDefaultNotificationSettings(): NotificationSettings {
  return {
    telegramEnabled: false,
    telegramBotToken: "",
    telegramChatId: "",
    lowStock: createNotificationRuleSettings(),
    nearExpiry: createNotificationRuleSettings(),
    expired: createNotificationRuleSettings({ telegram: true }),
    approvalRequests: createNotificationRuleSettings({ telegram: true }),
    failedSync: createNotificationRuleSettings({ telegram: true }),
    wastageThresholdExceeded: createNotificationRuleSettings({ telegram: true }),
    dailySummary: createDailySummarySettings(),
    wastageCostThreshold: 5000,
    style: createNotificationStyleSettings(),
    templates: createNotificationTemplates(),
  };
}
