import {
  createDefaultNotificationSettings,
  createDefaultReportPrintTemplate,
  DEFAULT_TIME_SOURCE,
} from "./defaults";
import { ROLE_PRESETS } from "./permissions";
import type {
  AppSettings,
  InventoryRequest,
  InventorySnapshot,
  Item,
  ItemStock,
  Location,
  MarketPriceEntry,
  MovementLedgerEntry,
  StockBatch,
  Supplier,
  User,
  WasteEntry,
} from "./types";

function isoBefore(hoursAgo: number): string {
  return new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString();
}

function isoAhead(daysAhead: number): string {
  return new Date(Date.now() + daysAhead * 24 * 60 * 60 * 1000).toISOString();
}

function isoDate(daysOffset = 0): string {
  return new Date(Date.now() + daysOffset * 24 * 60 * 60 * 1000)
    .toISOString()
    .slice(0, 10);
}

function prefixedId(prefix: string, value: number): string {
  return `${prefix}-${String(value).padStart(5, "0")}`;
}

let batchSequence = 1;

function makeStock(
  locationId: string,
  reserved: number,
  minLevel: number,
  maxLevel: number,
  batches: Array<Omit<StockBatch, "id" | "locationId">>,
): ItemStock {
  const normalizedBatches = batches.map((batch) => ({
    id: prefixedId("bat", batchSequence++),
    locationId,
    lotCode: batch.lotCode,
    quantity: batch.quantity,
    receivedAt: batch.receivedAt,
    expiryDate: batch.expiryDate,
  }));

  return {
    locationId,
    onHand: normalizedBatches.reduce((sum, batch) => sum + batch.quantity, 0),
    reserved,
    minLevel,
    maxLevel,
    batches: normalizedBatches,
  };
}

const locations: Location[] = [
  {
    id: "loc-00001",
    code: "KHI-CENTRAL",
    name: "Karachi Central Warehouse",
    type: "warehouse",
    city: "Karachi",
    status: "active",
  },
  {
    id: "loc-00002",
    code: "LHE-NORTH",
    name: "Lahore North Warehouse",
    type: "warehouse",
    city: "Lahore",
    status: "active",
  },
  {
    id: "loc-00003",
    code: "ISB-HUB",
    name: "Islamabad Distribution Hub",
    type: "warehouse",
    city: "Islamabad",
    status: "active",
  },
  {
    id: "loc-00004",
    code: "OUT-DHA",
    name: "DHA Outlet",
    type: "outlet",
    city: "Karachi",
    status: "active",
  },
  {
    id: "loc-00005",
    code: "OUT-GBG",
    name: "Gulberg Outlet",
    type: "outlet",
    city: "Lahore",
    status: "active",
  },
];

const suppliers: Supplier[] = [
  {
    id: "sup-00001",
    code: "SUP-001",
    name: "Rice Hub Traders",
    email: "ops@ricehub.example",
    phone: "+92-300-0001001",
    leadTimeDays: 3,
    status: "active",
  },
  {
    id: "sup-00002",
    code: "SUP-002",
    name: "Sunrise Oil Corporation",
    email: "dispatch@sunriseoil.example",
    phone: "+92-300-0001002",
    leadTimeDays: 4,
    status: "active",
  },
  {
    id: "sup-00003",
    code: "SUP-003",
    name: "Packline Essentials",
    email: "sales@packline.example",
    phone: "+92-300-0001003",
    leadTimeDays: 2,
    status: "active",
  },
];

const items: Item[] = [
  {
    id: "itm-00001",
    sku: "OMN-RICE-25",
    barcode: "8964000000001",
    name: "Basmati Rice 25kg",
    category: "Dry Goods",
    unit: "bag",
    supplierId: "sup-00001",
    costPrice: 7800,
    sellingPrice: 9150,
    status: "active",
    updatedAt: isoBefore(1),
    stocks: [
      makeStock("loc-00001", 4, 25, 140, [
        { lotCode: "RICE-KHI-2401", quantity: 40, receivedAt: isoBefore(24 * 90), expiryDate: isoAhead(180) },
        { lotCode: "RICE-KHI-2402", quantity: 44, receivedAt: isoBefore(24 * 48), expiryDate: isoAhead(75) },
      ]),
      makeStock("loc-00002", 2, 20, 100, [
        { lotCode: "RICE-LHE-2401", quantity: 30, receivedAt: isoBefore(24 * 70), expiryDate: isoAhead(60) },
        { lotCode: "RICE-LHE-2402", quantity: 22, receivedAt: isoBefore(24 * 30), expiryDate: isoAhead(210) },
      ]),
      makeStock("loc-00004", 0, 6, 20, [
        { lotCode: "RICE-DHA-2401", quantity: 5, receivedAt: isoBefore(24 * 36), expiryDate: isoAhead(20) },
        { lotCode: "RICE-DHA-2402", quantity: 7, receivedAt: isoBefore(24 * 18), expiryDate: isoAhead(95) },
      ]),
    ],
  },
  {
    id: "itm-00002",
    sku: "OMN-OIL-05",
    barcode: "8964000000002",
    name: "Sunflower Oil 5L",
    category: "Cooking Oil",
    unit: "bottle",
    supplierId: "sup-00002",
    costPrice: 1450,
    sellingPrice: 1750,
    status: "active",
    updatedAt: isoBefore(2),
    stocks: [
      makeStock("loc-00001", 8, 36, 200, [
        { lotCode: "OIL-KHI-2401", quantity: 70, receivedAt: isoBefore(24 * 45), expiryDate: isoAhead(25) },
        { lotCode: "OIL-KHI-2402", quantity: 60, receivedAt: isoBefore(24 * 12), expiryDate: isoAhead(90) },
      ]),
      makeStock("loc-00003", 6, 24, 140, [
        { lotCode: "OIL-ISB-2401", quantity: 30, receivedAt: isoBefore(24 * 30), expiryDate: isoAhead(9) },
        { lotCode: "OIL-ISB-2402", quantity: 45, receivedAt: isoBefore(24 * 16), expiryDate: isoAhead(55) },
      ]),
      makeStock("loc-00005", 1, 10, 28, [
        { lotCode: "OIL-GBG-2400", quantity: 6, receivedAt: isoBefore(24 * 60), expiryDate: isoAhead(-2) },
        { lotCode: "OIL-GBG-2401", quantity: 12, receivedAt: isoBefore(24 * 14), expiryDate: isoAhead(6) },
      ]),
    ],
  },
  {
    id: "itm-00003",
    sku: "OMN-SPC-500",
    barcode: "8964000000003",
    name: "Cardamom 500g",
    category: "Spices",
    unit: "jar",
    supplierId: "sup-00001",
    costPrice: 980,
    sellingPrice: 1210,
    status: "active",
    updatedAt: isoBefore(4),
    stocks: [
      makeStock("loc-00001", 1, 18, 40, [
        { lotCode: "SPC-KHI-2401", quantity: 12, receivedAt: isoBefore(24 * 32), expiryDate: isoAhead(40) },
        { lotCode: "SPC-KHI-2402", quantity: 10, receivedAt: isoBefore(24 * 10), expiryDate: isoAhead(150) },
      ]),
      makeStock("loc-00002", 0, 14, 35, [
        { lotCode: "SPC-LHE-2401", quantity: 4, receivedAt: isoBefore(24 * 28), expiryDate: isoAhead(5) },
        { lotCode: "SPC-LHE-2402", quantity: 7, receivedAt: isoBefore(24 * 14), expiryDate: isoAhead(35) },
      ]),
      makeStock("loc-00004", 0, 6, 15, [
        { lotCode: "SPC-DHA-2399", quantity: 2, receivedAt: isoBefore(24 * 44), expiryDate: isoAhead(-1) },
        { lotCode: "SPC-DHA-2401", quantity: 3, receivedAt: isoBefore(24 * 7), expiryDate: isoAhead(4) },
      ]),
    ],
  },
  {
    id: "itm-00004",
    sku: "OMN-PKG-100",
    barcode: "8964000000004",
    name: "Disposable Cups x100",
    category: "Packaging",
    unit: "pack",
    supplierId: "sup-00003",
    costPrice: 240,
    sellingPrice: 320,
    status: "active",
    updatedAt: isoBefore(3),
    stocks: [
      makeStock("loc-00001", 15, 70, 280, [
        { lotCode: "PKG-KHI-2401", quantity: 120, receivedAt: isoBefore(24 * 60) },
        { lotCode: "PKG-KHI-2402", quantity: 85, receivedAt: isoBefore(24 * 18) },
      ]),
      makeStock("loc-00003", 12, 48, 220, [
        { lotCode: "PKG-ISB-2401", quantity: 80, receivedAt: isoBefore(24 * 42) },
        { lotCode: "PKG-ISB-2402", quantity: 60, receivedAt: isoBefore(24 * 20) },
      ]),
      makeStock("loc-00005", 2, 12, 40, [
        { lotCode: "PKG-GBG-2401", quantity: 10, receivedAt: isoBefore(24 * 25) },
        { lotCode: "PKG-GBG-2402", quantity: 16, receivedAt: isoBefore(24 * 9) },
      ]),
    ],
  },
  {
    id: "itm-00005",
    sku: "OMN-SNK-CASE",
    barcode: "8964000000005",
    name: "Butter Biscuit Case",
    category: "Snacks",
    unit: "case",
    supplierId: "sup-00003",
    costPrice: 1800,
    sellingPrice: 2190,
    status: "active",
    updatedAt: isoBefore(5),
    stocks: [
      makeStock("loc-00002", 3, 20, 70, [
        { lotCode: "SNK-LHE-2401", quantity: 18, receivedAt: isoBefore(24 * 20), expiryDate: isoAhead(14) },
        { lotCode: "SNK-LHE-2402", quantity: 20, receivedAt: isoBefore(24 * 6), expiryDate: isoAhead(65) },
      ]),
      makeStock("loc-00003", 2, 18, 60, [
        { lotCode: "SNK-ISB-2401", quantity: 9, receivedAt: isoBefore(24 * 22), expiryDate: isoAhead(2) },
        { lotCode: "SNK-ISB-2402", quantity: 20, receivedAt: isoBefore(24 * 8), expiryDate: isoAhead(48) },
      ]),
      makeStock("loc-00004", 1, 8, 18, [
        { lotCode: "SNK-DHA-2399", quantity: 4, receivedAt: isoBefore(24 * 35), expiryDate: isoAhead(-3) },
        { lotCode: "SNK-DHA-2401", quantity: 5, receivedAt: isoBefore(24 * 5), expiryDate: isoAhead(8) },
      ]),
    ],
  },
  {
    id: "itm-00006",
    sku: "OMN-HM-3L",
    barcode: "8964000000006",
    name: "Floor Detergent 3L",
    category: "Household",
    unit: "bottle",
    supplierId: "sup-00003",
    costPrice: 650,
    sellingPrice: 830,
    status: "active",
    updatedAt: isoBefore(6),
    stocks: [
      makeStock("loc-00001", 1, 18, 48, [
        { lotCode: "HM-KHI-2401", quantity: 6, receivedAt: isoBefore(24 * 28), expiryDate: isoAhead(12) },
        { lotCode: "HM-KHI-2402", quantity: 11, receivedAt: isoBefore(24 * 11), expiryDate: isoAhead(100) },
      ]),
      makeStock("loc-00002", 2, 14, 50, [
        { lotCode: "HM-LHE-2401", quantity: 9, receivedAt: isoBefore(24 * 26), expiryDate: isoAhead(35) },
        { lotCode: "HM-LHE-2402", quantity: 17, receivedAt: isoBefore(24 * 10), expiryDate: isoAhead(140) },
      ]),
      makeStock("loc-00005", 0, 5, 12, [
        { lotCode: "HM-GBG-2401", quantity: 7, receivedAt: isoBefore(24 * 13), expiryDate: isoAhead(4) },
      ]),
    ],
  },
];

function makeUser(
  id: string,
  name: string,
  username: string,
  email: string,
  role: User["role"],
  assignedLocationIds: string[],
  lastSeenHoursAgo: number,
): User {
  return {
    id,
    name,
    username,
    email,
    role,
    permissions: ROLE_PRESETS[role].permissions,
    assignedLocationIds,
    status: "active",
    lastSeenAt: isoBefore(lastSeenHoursAgo),
  };
}

const users: User[] = [
  makeUser(
    "usr-00001",
    "Amina Shah",
    "amina.shah",
    "amina@omnistock.example",
    "superadmin",
    ["loc-00001", "loc-00002", "loc-00003"],
    1,
  ),
  makeUser(
    "usr-00002",
    "Bilal Ahmed",
    "bilal.ahmed",
    "bilal@omnistock.example",
    "admin",
    ["loc-00001", "loc-00003"],
    2,
  ),
  makeUser(
    "usr-00003",
    "Hina Khan",
    "hina.khan",
    "hina@omnistock.example",
    "manager",
    ["loc-00002", "loc-00005"],
    4,
  ),
  makeUser(
    "usr-00004",
    "Umair Ali",
    "umair.ali",
    "umair@omnistock.example",
    "worker",
    ["loc-00001", "loc-00004"],
    6,
  ),
];

const rolePermissions: InventorySnapshot["rolePermissions"] = {
  superadmin: [...ROLE_PRESETS.superadmin.permissions],
  admin: [...ROLE_PRESETS.admin.permissions],
  manager: [...ROLE_PRESETS.manager.permissions],
  worker: [...ROLE_PRESETS.worker.permissions],
};

const marketPrices: MarketPriceEntry[] = [
  {
    id: "mpr-00001",
    marketDate: isoDate(-2),
    category: "dry-goods",
    itemId: "itm-00001",
    itemName: "Basmati Rice 25kg",
    locationId: "loc-00001",
    locationName: "Karachi Central Warehouse",
    supplierId: "sup-00001",
    supplierName: "Rice Hub Traders",
    unit: "bag",
    quotedPrice: 7650,
    sourceName: "Jodia Bazaar morning sheet",
    note: "Pre-Ramadan wholesale quote from preferred rice traders.",
    capturedBy: "usr-00002",
    capturedByName: "Bilal Ahmed",
    createdAt: isoBefore(52),
  },
  {
    id: "mpr-00002",
    marketDate: isoDate(-1),
    category: "dry-goods",
    itemId: "itm-00001",
    itemName: "Basmati Rice 25kg",
    locationId: "loc-00001",
    locationName: "Karachi Central Warehouse",
    supplierId: "sup-00001",
    supplierName: "Rice Hub Traders",
    unit: "bag",
    quotedPrice: 7800,
    previousPrice: 7650,
    variancePct: 1.96,
    sourceName: "Wholesale follow-up call",
    note: "Supplier revised the rate after transport increase.",
    capturedBy: "usr-00002",
    capturedByName: "Bilal Ahmed",
    createdAt: isoBefore(26),
  },
  {
    id: "mpr-00003",
    marketDate: isoDate(-1),
    category: "oil",
    itemId: "itm-00002",
    itemName: "Sunflower Oil 5L",
    locationId: "loc-00003",
    locationName: "Islamabad Distribution Hub",
    supplierId: "sup-00002",
    supplierName: "Sunrise Oil Corporation",
    unit: "bottle",
    quotedPrice: 1425,
    sourceName: "Islamabad edible oil board",
    note: "Bulk quote checked against northern region supply.",
    capturedBy: "usr-00003",
    capturedByName: "Hina Khan",
    createdAt: isoBefore(20),
  },
  {
    id: "mpr-00004",
    marketDate: isoDate(0),
    category: "dry-goods",
    itemId: "itm-00003",
    itemName: "Cardamom 500g",
    locationId: "loc-00002",
    locationName: "Lahore North Warehouse",
    supplierId: "sup-00001",
    supplierName: "Rice Hub Traders",
    unit: "jar",
    quotedPrice: 1020,
    previousPrice: 980,
    variancePct: 4.08,
    sourceName: "Akbari Mandi spice survey",
    note: "Spice merchants reported tighter arrivals this morning.",
    capturedBy: "usr-00003",
    capturedByName: "Hina Khan",
    createdAt: isoBefore(6),
  },
];

const requests: InventoryRequest[] = [
  {
    id: "req-00001",
    reference: "GRN-1001",
    kind: "grn",
    status: "submitted",
    itemId: "itm-00001",
    itemName: "Basmati Rice 25kg",
    barcode: "8964000000001",
    quantity: 20,
    unit: "bag",
    supplierId: "sup-00001",
    supplierName: "Rice Hub Traders",
    toLocationId: "loc-00001",
    toLocationName: "Karachi Central Warehouse",
    lotCode: "RICE-KHI-2403",
    expiryDate: isoAhead(160),
    receivedDate: isoBefore(12),
    note: "Inbound PO for Ramadan safety stock.",
    requestedBy: "usr-00002",
    requestedByName: "Bilal Ahmed",
    requestedAt: isoBefore(12),
  },
  {
    id: "req-00002",
    reference: "GIN-1002",
    kind: "gin",
    status: "posted",
    itemId: "itm-00002",
    itemName: "Sunflower Oil 5L",
    barcode: "8964000000002",
    quantity: 18,
    unit: "bottle",
    fromLocationId: "loc-00003",
    fromLocationName: "Islamabad Distribution Hub",
    allocationSummary: "FEFO issued from OIL-ISB-2401 (18 bottles).",
    note: "Outlet replenishment batch 22.",
    requestedBy: "usr-00003",
    requestedByName: "Hina Khan",
    requestedAt: isoBefore(18),
  },
  {
    id: "req-00003",
    reference: "TRF-1003",
    kind: "transfer",
    status: "submitted",
    itemId: "itm-00004",
    itemName: "Disposable Cups x100",
    barcode: "8964000000004",
    quantity: 24,
    unit: "pack",
    fromLocationId: "loc-00001",
    fromLocationName: "Karachi Central Warehouse",
    toLocationId: "loc-00003",
    toLocationName: "Islamabad Distribution Hub",
    note: "Balancing packaging levels ahead of weekend dispatch.",
    requestedBy: "usr-00002",
    requestedByName: "Bilal Ahmed",
    requestedAt: isoBefore(20),
  },
  {
    id: "req-00004",
    reference: "ADJ-1004",
    kind: "adjustment",
    status: "posted",
    itemId: "itm-00006",
    itemName: "Floor Detergent 3L",
    barcode: "8964000000006",
    quantity: -2,
    unit: "bottle",
    fromLocationId: "loc-00001",
    fromLocationName: "Karachi Central Warehouse",
    note: "Damaged during unloading.",
    requestedBy: "usr-00004",
    requestedByName: "Umair Ali",
    requestedAt: isoBefore(28),
  },
  {
    id: "req-00005",
    reference: "CNT-1005",
    kind: "stock-count",
    status: "submitted",
    itemId: "itm-00003",
    itemName: "Cardamom 500g",
    barcode: "8964000000003",
    quantity: 10,
    unit: "jar",
    fromLocationId: "loc-00002",
    fromLocationName: "Lahore North Warehouse",
    allocationSummary: "Cycle count flagged short shelf-life jars in lot SPC-LHE-2401.",
    note: "Cycle count discrepancy waiting review.",
    requestedBy: "usr-00003",
    requestedByName: "Hina Khan",
    requestedAt: isoBefore(30),
  },
  {
    id: "req-00006",
    reference: "WST-1006",
    kind: "wastage",
    status: "posted",
    itemId: "itm-00005",
    itemName: "Butter Biscuit Case",
    barcode: "8964000000005",
    quantity: 2,
    unit: "case",
    fromLocationId: "loc-00004",
    fromLocationName: "DHA Outlet",
    allocationSummary: "Wastage removed from SNK-DHA-2399 (2).",
    wasteReason: "expiry",
    wasteShift: "night",
    wasteStation: "Outlet pantry",
    note: "Expired display stock removed after closing checks.",
    requestedBy: "usr-00004",
    requestedByName: "Umair Ali",
    requestedAt: isoBefore(8),
  },
];

const wasteEntries: WasteEntry[] = [
  {
    id: "wte-00001",
    requestId: "req-00006",
    itemId: "itm-00005",
    itemName: "Butter Biscuit Case",
    locationId: "loc-00004",
    locationName: "DHA Outlet",
    quantity: 2,
    unit: "case",
    reason: "expiry",
    shift: "night",
    station: "Outlet pantry",
    batchLotCode: "SNK-DHA-2399",
    expiryDate: isoAhead(-3),
    estimatedCost: 3600,
    reportedBy: "usr-00004",
    reportedByName: "Umair Ali",
    createdAt: isoBefore(8),
    note: "Expired display stock removed after closing checks.",
  },
];

const movementLedger: MovementLedgerEntry[] = [
  {
    id: "led-00006",
    reference: "WST-1006",
    itemId: "itm-00005",
    itemName: "Butter Biscuit Case",
    locationId: "loc-00004",
    locationName: "DHA Outlet",
    changeType: "wastage",
    quantityBefore: 11,
    quantityChange: -2,
    quantityAfter: 9,
    actorId: "usr-00004",
    actorName: "Umair Ali",
    createdAt: isoBefore(8),
    allocationSummary: "Wastage removed from SNK-DHA-2399 (2).",
    note: "Expired display stock removed after closing checks.",
  },
  {
    id: "led-00001",
    reference: "GIN-1002",
    itemId: "itm-00002",
    itemName: "Sunflower Oil 5L",
    locationId: "loc-00003",
    locationName: "Islamabad Distribution Hub",
    changeType: "gin",
    quantityBefore: 93,
    quantityChange: -18,
    quantityAfter: 75,
    actorId: "usr-00003",
    actorName: "Hina Khan",
    createdAt: isoBefore(18),
    note: "Outlet replenishment batch 22.",
  },
  {
    id: "led-00002",
    reference: "ADJ-1004",
    itemId: "itm-00006",
    itemName: "Floor Detergent 3L",
    locationId: "loc-00001",
    locationName: "Karachi Central Warehouse",
    changeType: "adjustment",
    quantityBefore: 19,
    quantityChange: -2,
    quantityAfter: 17,
    actorId: "usr-00004",
    actorName: "Umair Ali",
    createdAt: isoBefore(28),
    note: "Damaged during unloading.",
  },
  {
    id: "led-00003",
    reference: "GIN-0998",
    itemId: "itm-00001",
    itemName: "Basmati Rice 25kg",
    locationId: "loc-00004",
    locationName: "DHA Outlet",
    changeType: "gin",
    quantityBefore: 17,
    quantityChange: -5,
    quantityAfter: 12,
    actorId: "usr-00004",
    actorName: "Umair Ali",
    createdAt: isoBefore(32),
    note: "Retail replenishment.",
  },
  {
    id: "led-00004",
    reference: "GRN-0997",
    itemId: "itm-00005",
    itemName: "Butter Biscuit Case",
    locationId: "loc-00003",
    locationName: "Islamabad Distribution Hub",
    changeType: "grn",
    quantityBefore: 12,
    quantityChange: 17,
    quantityAfter: 29,
    actorId: "usr-00002",
    actorName: "Bilal Ahmed",
    createdAt: isoBefore(40),
    note: "Supplier backorder landed.",
  },
  {
    id: "led-00005",
    reference: "TRF-0996",
    itemId: "itm-00004",
    itemName: "Disposable Cups x100",
    locationId: "loc-00001",
    locationName: "Karachi Central Warehouse",
    changeType: "transfer",
    quantityBefore: 224,
    quantityChange: -19,
    quantityAfter: 205,
    actorId: "usr-00002",
    actorName: "Bilal Ahmed",
    createdAt: isoBefore(42),
    note: "Backfill Islamabad hub.",
  },
];

const settings: AppSettings = {
  companyName: "OmniStock Demo Holdings",
  currency: "PKR",
  timezone: "Asia/Karachi",
  timeSource: DEFAULT_TIME_SOURCE,
  lowStockThreshold: 1,
  expiryAlertDays: 14,
  enableOffline: true,
  enableRealtime: true,
  enableBarcode: true,
  strictFefo: true,
  reportPrintTemplate: createDefaultReportPrintTemplate("OmniStock Demo Holdings"),
  notificationSettings: createDefaultNotificationSettings(),
};

export function createSeedSnapshot(): InventorySnapshot {
  return {
    generatedAt: new Date().toISOString(),
    syncCursor: 13,
    items: structuredClone(items),
    suppliers: structuredClone(suppliers),
    marketPrices: structuredClone(marketPrices),
    wasteEntries: structuredClone(wasteEntries),
    locations: structuredClone(locations),
    users: structuredClone(users),
    requests: structuredClone(requests),
    movementLedger: structuredClone(movementLedger),
    notifications: [],
    rolePermissions: structuredClone(rolePermissions),
    activity: [
      {
        id: "act-00013",
        seq: 13,
        title: "Wastage logged",
        detail: "Expired biscuit cases were written off from the DHA outlet pantry.",
        actorId: "usr-00004",
        actorName: "Umair Ali",
        createdAt: isoBefore(8),
        module: "reports",
        severity: "warning",
      },
      {
        id: "act-00007",
        seq: 12,
        title: "GRN awaiting confirmation",
        detail: "Inbound rice stock request queued at Karachi Central Warehouse.",
        actorId: "usr-00002",
        actorName: "Bilal Ahmed",
        createdAt: isoBefore(12),
        module: "inventoryOps",
        severity: "warning",
      },
      {
        id: "act-00008",
        seq: 11,
        title: "GIN posted",
        detail: "Islamabad outbound issue completed for Sunflower Oil 5L.",
        actorId: "usr-00003",
        actorName: "Hina Khan",
        createdAt: isoBefore(18),
        module: "inventoryOps",
        severity: "success",
      },
      {
        id: "act-00009",
        seq: 10,
        title: "Transfer requested",
        detail: "Packaging stock transfer raised from Karachi to Islamabad.",
        actorId: "usr-00002",
        actorName: "Bilal Ahmed",
        createdAt: isoBefore(20),
        module: "inventoryOps",
        severity: "info",
      },
      {
        id: "act-00010",
        seq: 9,
        title: "Damage adjustment posted",
        detail: "Two detergent bottles marked damaged on receiving.",
        actorId: "usr-00004",
        actorName: "Umair Ali",
        createdAt: isoBefore(28),
        module: "inventoryOps",
        severity: "warning",
      },
      {
        id: "act-00011",
        seq: 8,
        title: "Cycle count pending review",
        detail: "Cardamom count discrepancy needs manager approval in Lahore.",
        actorId: "usr-00003",
        actorName: "Hina Khan",
        createdAt: isoBefore(30),
        module: "reports",
        severity: "warning",
      },
      {
        id: "act-00012",
        seq: 7,
        title: "Role audit completed",
        detail: "Daily activity export generated for admin review.",
        actorId: "usr-00001",
        actorName: "Amina Shah",
        createdAt: isoBefore(36),
        module: "administration",
        severity: "success",
      },
    ],
    settings: structuredClone(settings),
  };
}

export function createEmptySnapshot(): InventorySnapshot {
  return {
    generatedAt: new Date().toISOString(),
    syncCursor: 0,
    items: [],
    suppliers: [],
    marketPrices: [],
    wasteEntries: [],
    locations: [],
    users: [],
    requests: [],
    movementLedger: [],
    activity: [],
    rolePermissions: {
      superadmin: [...ROLE_PRESETS.superadmin.permissions],
      admin: [...ROLE_PRESETS.admin.permissions],
      manager: [...ROLE_PRESETS.manager.permissions],
      worker: [...ROLE_PRESETS.worker.permissions],
    },
    settings: {
      companyName: "OmniStock",
      currency: "PKR",
      timezone: "Asia/Karachi",
      timeSource: DEFAULT_TIME_SOURCE,
      lowStockThreshold: 5,
      expiryAlertDays: 14,
      enableOffline: true,
      enableRealtime: true,
      enableBarcode: true,
      strictFefo: true,
      reportPrintTemplate: createDefaultReportPrintTemplate("OmniStock"),
      notificationSettings: createDefaultNotificationSettings(),
    },
    notifications: [],
  };
}
